title: On the Trail of the Sin-Eater
author: Tony Hirst
copyright: "2021" 
only_build_toc_files: true

execute:
  execute_notebooks: cache
  timeout: 60  
parse:
  myst_dmath_double_inline: true

bibtex_bibfiles:
    - _references_books.bib

sphinx:
  config:
    html_copy_source: false
    bibtex_reference_style: author_year
  extra_extensions:
